---
- hosts: cluster
  tasks:
  - name: Adicionar pacotes pré-requisitos
    apt: 
        name: ['apt-transport-https','ca-certificates','curl','gnupg','software-properties-common   ']     
    become: yes
  - name: Adicionar a chave GPG para o repositório oficial do Docker no seu sistema
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    become: yes
  - name: Adicionar repositório Docker
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    become: yes
  - name: Update no repositório de pacotes e instalação do Docker
    apt:
        update_cache: yes
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    become: yes
  - name: Adicionar usuário ao grupo Docker
    user: 
        name: ubuntu
        groups: docker
        append: yes
    become: yes
